import { Themes } from './types/theme'

export const themes: Themes = {
  light: {
    background: '#fff',
    color: '#444',
    boardColumnColor: '#f5f5f5',
    taskCardColor: '#fff',
    subtaskCardColor: '#f5f5f5',
    sidebarColor: '#f5f5f5',
    currentBoardColor: '#e9e9e9',
    currentBoardShadowColor: '#aaa',
    calendarArrowBackground: '#f5f5f5',
    calendarHeaderColor: '#f5f5f5',
    calendarDayColor: '#fff',
    calendarTaskColor: '#f5f5f5',
    calendarOverlayColor: '#fff',
    datePickerArrowColor: '#444',
    datePickerColor: '#000',
    datePickerBackground: '#fff',
    datePickerSelectedDayColor: '#000',
    datePickerSelectedDayBackground: '#f5f5f5',
  },
  dark: {
    background: '#202127',
    color: '#ddd',
    boardColumnColor: '#2c2c35',
    taskCardColor: '#44444f',
    subtaskCardColor: '#595964',
    sidebarColor: '#2c2c35',
    currentBoardColor: '#44444f',
    currentBoardShadowColor: '#000',
    calendarArrowBackground: '#44444f',
    calendarHeaderColor: '#44444f',
    calendarDayColor: '#2c2c35',
    calendarTaskColor: '#44444f',
    calendarOverlayColor: '#2c2c35',
    datePickerArrowColor: '#fff',
    datePickerColor: '#fff',
    datePickerBackground: '#2c2c35',
    datePickerSelectedDayColor: '#fff',
    datePickerSelectedDayBackground: '#44444f',
  },
}
